'use client';

export interface EditorBlock { id?: string; day_number: number; item_order: number; title: string; description: string; category: string; period: 'morning' | 'afternoon' | 'night' | 'any'; is_required: boolean; agency_notes?: string; ai_instructions?: string; tags?: string[]; }
export interface EditorDay { id?: string; day_number: number; title: string; rain_alternatives?: string; meals_recommendation?: Array<Record<string, unknown>>; }

export function TemplateEditor({ days, blocks, onDaysChange, onBlocksChange }: { days: EditorDay[]; blocks: EditorBlock[]; onDaysChange: (days: EditorDay[]) => void; onBlocksChange: (blocks: EditorBlock[]) => void; }) {
  const addDay = () => { const day = Math.max(0, ...days.map((item) => item.day_number)) + 1; onDaysChange([...days, { day_number: day, title: `Dia ${day}`, rain_alternatives: '' }]); };
  const updateBlock = (index: number, patch: Partial<EditorBlock>) => onBlocksChange(blocks.map((block, position) => position === index ? { ...block, ...patch } : block));
  return <div className="space-y-4">
    {days.map((day) => <section key={day.day_number} className="rounded-2xl border border-primary/10 bg-surface-container-low p-4">
      <div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary text-xs font-black text-white">{day.day_number}</span><input value={day.title} onChange={(event) => onDaysChange(days.map((item) => item.day_number === day.day_number ? { ...item, title: event.target.value } : item))} className="min-w-0 flex-1 rounded-xl border border-outline-variant bg-white p-2.5 text-xs font-bold"/><button onClick={() => onBlocksChange([...blocks, { day_number: day.day_number, item_order: blocks.filter((item) => item.day_number === day.day_number).length, title: 'Nova atividade', description: '', category: 'activity', period: 'morning', is_required: false }])} type="button" className="rounded-xl border border-primary/15 px-3 py-2 text-[10px] font-bold text-primary">+ Bloco</button></div>
      <div className="mt-3 grid gap-2 md:grid-cols-3">{(['morning','afternoon','night'] as const).map((period) => <div key={period} className="rounded-xl border border-outline-variant bg-white p-3"><p className="mb-2 text-[9px] font-black uppercase tracking-wider text-primary">{period === 'morning' ? 'Manhã' : period === 'afternoon' ? 'Tarde' : 'Noite'}</p><div className="space-y-2">{blocks.map((block, index) => ({ block, index })).filter(({ block }) => block.day_number === day.day_number && (block.period === period || block.period === 'any')).map(({ block, index }) => <div key={block.id || `${day.day_number}-${index}`} className="rounded-lg bg-ice-blue p-2.5"><input value={block.title} onChange={(event) => updateBlock(index, { title: event.target.value })} className="w-full bg-transparent text-[10px] font-bold outline-none"/><div className="mt-2 flex items-center justify-between"><label className="flex items-center gap-1 text-[8px] font-semibold"><input type="checkbox" checked={block.is_required} onChange={(event) => updateBlock(index, { is_required: event.target.checked })}/>Obrigatório</label><button type="button" onClick={() => onBlocksChange(blocks.filter((_, position) => position !== index))} className="text-error"><span className="material-symbols-outlined text-[14px]">delete</span></button></div></div>)}</div></div>)}</div>
      <textarea value={day.rain_alternatives || ''} onChange={(event) => onDaysChange(days.map((item) => item.day_number === day.day_number ? { ...item, rain_alternatives: event.target.value } : item))} placeholder="Alternativas para chuva" className="mt-3 w-full rounded-xl border border-outline-variant bg-white p-3 text-[10px]"/>
    </section>)}
    <button type="button" onClick={addDay} className="w-full rounded-xl border border-dashed border-primary/25 p-3 text-xs font-bold text-primary hover:bg-ice-blue">Adicionar dia</button>
  </div>;
}
