const AMERICA_DESTINATION_OPTIONS = [
  "Alter do Chao (BR)",
  "Angra dos Reis (BR)",
  "Aparecida (BR)",
  "Aracaju (BR)",
  "Arraial do Cabo (BR)",
  "Balneario Camboriu (BR)",
  "Barreirinhas (BR)",
  "Belem (BR)",
  "Belo Horizonte (BR)",
  "Bento Goncalves (BR)",
  "Blumenau (BR)",
  "Bonito (BR)",
  "Brasilia (BR)",
  "Brotas (BR)",
  "Buzios (BR)",
  "Cabo Frio (BR)",
  "Caldas Novas (BR)",
  "Cambara do Sul (BR)",
  "Campinas (BR)",
  "Campo Grande (BR)",
  "Canela (BR)",
  "Chapada dos Guimaraes (BR)",
  "Chapada dos Veadeiros (BR)",
  "Curitiba (BR)",
  "Fernando de Noronha (BR)",
  "Florianopolis (BR)",
  "Fortaleza (BR)",
  "Foz do Iguacu (BR)",
  "Gramado (BR)",
  "Ilha Grande (BR)",
  "Ilhabela (BR)",
  "Itacare (BR)",
  "Jericoacoara (BR)",
  "Joao Pessoa (BR)",
  "Lencois (BR)",
  "Maceio (BR)",
  "Manaus (BR)",
  "Maragogi (BR)",
  "Morro de Sao Paulo (BR)",
  "Natal (BR)",
  "Olinda (BR)",
  "Ouro Preto (BR)",
  "Palmas (BR)",
  "Pantanal (BR)",
  "Paraty (BR)",
  "Petropolis (BR)",
  "Pipa (BR)",
  "Porto Alegre (BR)",
  "Porto de Galinhas (BR)",
  "Porto Seguro (BR)",
  "Praia do Forte (BR)",
  "Recife (BR)",
  "Rio de Janeiro (BR)",
  "Salvador (BR)",
  "Sao Luis (BR)",
  "Sao Paulo (BR)",
  "Tiradentes (BR)",
  "Trancoso (BR)",
  "Ubatuba (BR)",
  "Vitoria (BR)",
  "Bariloche (AR)",
  "Buenos Aires (AR)",
  "El Calafate (AR)",
  "Mendoza (AR)",
  "Patagonia Argentina (AR)",
  "Puerto Iguazu (AR)",
  "Salta (AR)",
  "Ushuaia (AR)",
  "La Paz (BO)",
  "Salar de Uyuni (BO)",
  "Sucre (BO)",
  "Atacama (CL)",
  "Ilha de Pascoa (CL)",
  "Patagonia Chilena (CL)",
  "Puerto Varas (CL)",
  "Santiago (CL)",
  "Valparaiso (CL)",
  "Bogota (CO)",
  "Cartagena (CO)",
  "Medellin (CO)",
  "San Andres (CO)",
  "Santa Marta (CO)",
  "Cuenca (EC)",
  "Galapagos (EC)",
  "Quito (EC)",
  "Assuncao (PY)",
  "Ciudad del Este (PY)",
  "Arequipa (PE)",
  "Cusco (PE)",
  "Lima (PE)",
  "Machu Picchu (PE)",
  "Nazca (PE)",
  "Vale Sagrado (PE)",
  "Colonia del Sacramento (UY)",
  "Montevideo (UY)",
  "Punta del Este (UY)",
  "Caracas (VE)",
  "Ilha Margarita (VE)",
  "Los Roques (VE)",
  "Georgetown (GY)",
  "Paramaribo (SR)",
  "Caiena (GF)",
  "Belize City (BZ)",
  "Caye Caulker (BZ)",
  "San Pedro Ambergris Caye (BZ)",
  "La Fortuna (CR)",
  "Manuel Antonio (CR)",
  "Monteverde (CR)",
  "San Jose (CR)",
  "Tamarindo (CR)",
  "San Salvador (SV)",
  "Antigua Guatemala (GT)",
  "Cidade da Guatemala (GT)",
  "Lago Atitlan (GT)",
  "Tikal (GT)",
  "Roatan (HN)",
  "Tegucigalpa (HN)",
  "Granada (NI)",
  "Ilha de Ometepe (NI)",
  "Leon (NI)",
  "Managua (NI)",
  "Bocas del Toro (PA)",
  "Cidade do Panama (PA)",
  "San Blas (PA)",
  "Aruba (AW)",
  "Bonaire (BQ)",
  "Exuma (BS)",
  "Nassau (BS)",
  "Bridgetown (BB)",
  "Havana (CU)",
  "Trinidad (CU)",
  "Varadero (CU)",
  "Curacao (CW)",
  "Roseau (DM)",
  "St George's (GD)",
  "Montego Bay (JM)",
  "Negril (JM)",
  "Ocho Rios (JM)",
  "San Juan (PR)",
  "Punta Cana (DO)",
  "Santo Domingo (DO)",
  "Pitons (LC)",
  "St Maarten (SX)",
  "Providenciales (TC)",
  "St Thomas (VI)",
  "Banff (CA)",
  "Calgary (CA)",
  "Montreal (CA)",
  "Niagara Falls (CA)",
  "Ottawa (CA)",
  "Quebec City (CA)",
  "Toronto (CA)",
  "Vancouver (CA)",
  "Victoria (CA)",
  "Whistler (CA)",
  "Lake Louise (CA)",
  "Anchorage (US)",
  "Atlanta (US)",
  "Austin (US)",
  "Boston (US)",
  "Chicago (US)",
  "Dallas (US)",
  "Denver (US)",
  "Grand Canyon (US)",
  "Honolulu (US)",
  "Houston (US)",
  "Las Vegas (US)",
  "Los Angeles (US)",
  "Miami (US)",
  "Nashville (US)",
  "New Orleans (US)",
  "Nova York (US)",
  "Orlando (US)",
  "Philadelphia (US)",
  "San Diego (US)",
  "San Francisco (US)",
  "Seattle (US)",
  "Washington DC (US)",
  "Yellowstone (US)",
  "Yosemite (US)",
  "Monument Valley (US)",
  "Mount Rushmore (US)",
  "Zion National Park (US)",
  "Cancun (MX)",
  "Cidade do Mexico (MX)",
  "Cozumel (MX)",
  "Guadalajara (MX)",
  "Los Cabos (MX)",
  "Merida (MX)",
  "Oaxaca (MX)",
  "Playa del Carmen (MX)",
  "Puerto Vallarta (MX)",
  "Riviera Maya (MX)",
  "San Miguel de Allende (MX)",
  "Tulum (MX)",
  "Barcelona (ES)",
  "Florença (IT)",
  "Lisboa (PT)",
  "Londres (GB)",
  "Madrid (ES)",
  "Milao (IT)",
  "Paris (FR)",
  "Roma (IT)",
  "Toquio (JP)",
  "Veneza (IT)"
];

export const AMERICA_DESTINATIONS = Array.from(new Set(
  AMERICA_DESTINATION_OPTIONS.filter((destination) => !destination.includes(' - '))
)).sort((a, b) => a.localeCompare(b, 'pt-BR'));
